<meta http-equiv="refresh" content="0;url=http://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl" />
<a href="http://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl">This page has moved.</a>
