#! /usr/bin/env python3
import os
import pathlib
import subprocess
import sys

DIR = pathlib.Path(__file__).parent

# -
# Extract the idl from index.html.

RESOURCES = DIR.parent.parent.parent / 'resources'
assert RESOURCES.exists(), RESOURCES
PYTHONPATH_LIBS = [
   RESOURCES / 'html5lib-1.1/src/html5lib',
   RESOURCES / 'webencodings-0.5.1/src/webencodings',
]
for lib in PYTHONPATH_LIBS:
   assert lib.exists(), lib
PYTHONPATH = os.pathsep.join([str(lib.parent) for lib in PYTHONPATH_LIBS])

ENV = os.environ
ENV['PYTHONPATH'] = PYTHONPATH

args = [sys.executable, 'extract-idl.py', 'index.html']
print(f'Running {args}...')
p = subprocess.run([sys.executable, 'extract-idl.py', 'index.html'], cwd=DIR, env=ENV, stdout=subprocess.PIPE, text=True)
p.check_returncode()
idl = p.stdout
assert '\r' not in idl

idl_file_data = '''\
// AUTOGENERATED FILE -- DO NOT EDIT -- SEE Makefile
//
// WebGL IDL definitions scraped from the Khronos specification:
// https://www.khronos.org/registry/webgl/specs/latest/
''' + idl

out_file = DIR / 'webgl2.idl'
print(f'Writing "{out_file}"...')
out_file.write_bytes(idl_file_data.encode())
